### ISSUE TITLE
step 5. command not working

### ISSUE THREAD

**Issue by pwnedzen** [TheFuseGamer/vs-codex#1]
Trying to set up the VS-codex extension on Mac. All step are working up until 

Step 5. To start vs code use code-insiders . --enable-proposed-api=fuse-gaming.vs-codex

when I run this command I get the error message: ```bash: code-insiders: command not found```

any ideas why this is, thanks

**Comment by TheFuseGamer** [comment]
Hello,
Thank you for your interest in the project. The inline completions are
still an experimental feature so you'll need to use the insiders edition
which you can download from here
https://code.visualstudio.com/insiders/
If you installed it and it still doesn't work, try restarting the terminal
or your computer.

**Comment by pwnedzen** [comment]
Already had this downloaded and installed ```https://code.visualstudio.com/insiders/```

and restarting terminal/computer did not help remediate the issue

**Comment by pwnedzen** [comment]
Bro thanks boss! All good up and running
