### ISSUE TITLE
Issue inputing the API

### ISSUE THREAD

**Issue by renanmb** [TheFuseGamer/vs-codex#2]
On the following step:
`code-insiders . --enable-proposed-api=fuse-gaming.vs-codex`

It opens the file: openai-api.ts
However I am slight confused of how to insert my API.

**Comment by amir-halloul** [comment]
You set your API key in the VS Code config (ctrl + ,) to open or via the cog icon at the bottom left.

**Comment by renanmb** [comment]
Also, is it necessary to create a environment variable?

**Comment by amir-halloul** [comment]
No. You just need to go to VS Code settings, search for "openai key", paste your API key in and that's it.

**Comment by amir-halloul** [comment]
I assume you figured out how to set your API key. I'll go ahead and close this issue.
Please feel free to open other issues if you need help with other matters.
