### ISSUE TITLE
Where is the vsix file?

### ISSUE THREAD

**Issue by Jeremy5909** [TheFuseGamer/vs-codex#4]
I just see the source code, how do I compile it or find the vsix file?

**Comment by amir-halloul** [comment]
You compile it like any other VS code extension.

1.  Install [VSCE](https://code.visualstudio.com/api/working-with-extensions/publishing-extension)
2. `cd path/to/extension`
3. `vsce package`

**Comment by Jeremy5909** [comment]
Thanks Im new to this sorta stuff

**Comment by Jeremy5909** [comment]
I get an error:

`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'compile'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.3
4 verbose run-script [ 'precompile', 'compile', 'postcompile' ]
5 info lifecycle vs-codex@0.0.1~precompile: vs-codex@0.0.1
6 info lifecycle vs-codex@0.0.1~compile: vs-codex@0.0.1
7 verbose lifecycle vs-codex@0.0.1~compile: unsafe-perm in lifecycle true
8 verbose lifecycle vs-codex@0.0.1~compile: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\jerem\Downloads\vs-codex\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\jerem\Downloads\vs-codex\node_modules\.bin;C:\Users\jerem\anaconda3\condabin;C:\Users\jerem\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\jerem\AppData\Local\Programs\Python\Python39\;C:\Program Files\Oculus\Support\oculus-runtime;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Users\jerem\AppData\Local\Programs\Microsoft VS Code\Code.exe;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Program Files\dotnet\;C:\Program Files\spwn\;C:\Users\jerem\anaconda3;C:\Users\jerem\anaconda3\Library\mingw-w64\bin;C:\Users\jerem\anaconda3\Library\usr\bin;C:\Users\jerem\anaconda3\Library\bin;C:\Users\jerem\anaconda3\Scripts;C:\Users\jerem\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.1\bin;;C:\Program Files\heroku\bin;C:\minGW\bin;A:\Users\jerem\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\jerem\AppData\Local\nvs\;C:\Users\jerem\AppData\Roaming\npm;C:\Users\jerem\.dotnet\tools
9 verbose lifecycle vs-codex@0.0.1~compile: CWD: C:\Users\jerem\Downloads\vs-codex
10 silly lifecycle vs-codex@0.0.1~compile: Args: [ '/d /s /c', 'tsc -p ./' ]
11 silly lifecycle vs-codex@0.0.1~compile: Returned: code: 1  signal: null
12 info lifecycle vs-codex@0.0.1~compile: Failed to exec compile script
13 verbose stack Error: vs-codex@0.0.1 compile: `tsc -p ./`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:375:28)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:375:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid vs-codex@0.0.1
15 verbose cwd C:\Users\jerem\Downloads\vs-codex
16 verbose Windows_NT 10.0.19043
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "compile"
18 verbose node v14.17.3
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 1
22 error vs-codex@0.0.1 compile: `tsc -p ./`
22 error Exit status 1
23 error Failed at the vs-codex@0.0.1 compile script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by amir-halloul** [comment]
Did you run `npm install`?

**Comment by amir-halloul** [comment]
I hope you get this issue resolved. I'll go ahead and close this one.
If you have any other problems, feel free to open a new issue.
